clc;
clear;
data_table = load('Training_table_resized.mat');
data_table=data_table.T;
options = trainingOptions('sgdm', ...
    'MaxEpochs', 3, ...
    'MiniBatchSize', 30, ...
    'InitialLearnRate', 1e-2, ...
    'CheckpointPath', tempdir,'ExecutionEnvironment','gpu','Shuffle','every-epoch','Momentum',0.9);%,'UseParallel','true');

[detector, info] = trainRCNNObjectDetector(data_table, 'resnet50',options,'NegativeOverlapRange', [0.1 0.3],'PositiveOverlapRange', [0.6 1]);
% [detector, info] = trainFasterRCNNObjectDetector(data_table, 'resnet50',options);
%         'NegativeOverlapRange', [0 0.3], ...
%         'PositiveOverlapRange', [0.6 1]);